# Example appveyor.xml file
# https://github.com/IlyaFinkelshteyn/CoreWebApplication1/blob/master/appveyor.yml

image: Visual Studio 2017

# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
#  author: jack@company.com        # Start a new build for commit of user with email jack@company.com


install:

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: cd ./pdf-merge-server
  # Display minimal restore text
  - cmd: dotnet restore
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build
test:
  - cmd: dotnet test

after_build:
- cmd: dotnet publish
